description: demo
gh_create: gh repo create tschm/wurst11 --public --description 'demo'
page: https://tschm.github.io/wurst11
project_name: wurst11
repository: https://github.com/tschm/wurst11
ssh_uri: git@github.com:tschm/wurst11.git
status: public
username: tschm
