description: Demo
gh_create: gh repo create tschm/wurst12 --public --description 'Demo'
page: https://tschm.github.io/wurst12
project_name: wurst12
repository: https://github.com/tschm/wurst12
ssh_uri: git@github.com:tschm/wurst12.git
status: public
username: tschm
