[project]
name = "cvxcli"
version = "0.0.0"
description = "Simple command line app demo"
readme = "README.md"
authors = [{name = "Thomas Schmelzer", email = "thomas.schmelzer@gmail.com"}]
requires-python = ">=3.10"
dependencies = [
"fire>=0.7.0",
"copier>=9.3.1",
"questionary>=2.0.1",
"loguru>=0.7.2",
"pygithub",
#typing_extensions = "*"
#pydantic_core = "*"
#annotated_types = "*"
"GitPython>=0.0.0"
]

[project.urls]
repository = "https://github.com/cvxgrp/cradle"

[dependency-groups]
dev = [
    "pytest-cov>=6.0.0",
    "pytest>=8.3.3",
    "pre-commit>=4.0.1",
]

[project.scripts]
cradle = "cvx.cradle.cli:cli"

[tool.ruff]
line-length = 120
target-version = "py310"
exclude = [
    "*__init__.py"
]

[tool.ruff.lint]
select = ["E", "F", "I"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["cvx"]
