name: pre-commit

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      - name: Load .env file
        uses: xom9ikk/dotenv@v2  # Dedicated action for loading .env files

      - uses: cvxgrp/.github/actions/uv/coverage@v2.0.3
        with:
          tests-folder: ${{ env.TEST_FOLDER }}
          source-folder: ${{ env.SOURCE_FOLDER }}

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2
        with:
          files: artifacts/tests/coverage/coverage.info
          format: lcov
