name: pre-commit

on:
  push:

permissions:
  checks: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: cvxgrp/.github/actions/uv/coverage@v2.0.17
        with:
          source-folder: src/cradle
          tests-folder: src/tests

  deptry:
    runs-on: ubuntu-latest
    steps:
      - uses: cvxgrp/.github/actions/uv/deptry@v2.0.17
        with:
          source-folder: src/cradle

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: cvxgrp/.github/actions/pre-commit@v2.1.0
